### ISSUE TITLE
please update   http: ^0.13.5 dependency 

### ISSUE THREAD

**Issue by magdyabdelaal97** [Mahad61/webviewx_plus#14]
Hi, can you please update the   http: ^0.13.5, it's causing a dependency conflict in my project, and it seem that http has to many updates after the used version in webviewx_plus

**Comment by PocketEngines** [comment]
I strongly agree. This is causing package incompatibilities, please resolve soon.

**Comment by jfr** [comment]
@Mahad61 can we assist you in updating the dependency?
